# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rofontai <rofontai@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/02 08:56:50 by rofontai          #+#    #+#              #
#    Updated: 2022/10/02 12:21:57 by rofontai         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
SRC = test2.c ft_fonction.c

all: comp

comp:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)
	
fclean:
	rm -f $(NAME)
	
exe:
	@./$(NAME)